api.name: catalog
server:
  port: 8201

# Spring Cloud  
spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  categoryChangeTopic
            content-type: application/json