version: '2'
services:
      
  inventory:
    image: fairanb/inventory-service:dev.v2.0
    container_name: inventory-service
    ports:
      - "8801:8801"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8801"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      AUTHENTICATION_SERVER_URI: "http://auth-service:8800/users/"
      KAFKA_SERVER_URI: "kafka-server"
      ZOOKEEPER_SERVER_URI: "kafka-server"
      DATABASE_SERVER_PORT: "3306"
      ELASTIC_SEARCH_PORT:  "9200"      
      EUREKA_SERVER_PORT:   "8761"
      ZUUL_SERVER_PORT:     "5555"
      KAFKA_SERVER_PORT:    "2181"
      REDIS_PORT:           "6379"
          
  merchant:
    ports:
      - "8802:8802"
    image: fairanb/merchant-service:dev.v2.0
    container_name: merchant-service
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8802"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      AUTHENTICATION_SERVER_URI: "http://auth-service:8800/users/"
      KAFKA_SERVER_URI: "kafka-server"
      ZOOKEEPER_SERVER_URI: "kafka-server"
      DATABASE_SERVER_PORT: "3306"
      ELASTIC_SEARCH_PORT:  "9200"      
      EUREKA_SERVER_PORT:   "8761"
      ZUUL_SERVER_PORT:     "5555"
      KAFKA_SERVER_PORT:    "2181"
      REDIS_PORT:           "6379"
      
  customer:
    ports:
      - "8803:8803"
    image: fairanb/customer-service:dev.v2.0
    container_name: customer-service
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8803"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      AUTHENTICATION_SERVER_URI: "http://auth-service:8800/users/"
      KAFKA_SERVER_URI: "kafka-server"
      ZOOKEEPER_SERVER_URI: "kafka-server"
      DATABASE_SERVER_PORT: "3306"
      ELASTIC_SEARCH_PORT:  "9200"      
      EUREKA_SERVER_PORT:   "8761"
      ZUUL_SERVER_PORT:     "5555"
      KAFKA_SERVER_PORT:    "2181"
      REDIS_PORT:           "6379"
      
  database-server:
    image: mysql
    container_name: database-server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=userdb
      - MYSQL_PASSWORD=Pass!234
      
  zuul-server:
    image: fairanb/zuul-server:dev.v2.0
    container_name: zuul-server
    ports:
      - "5555:5555"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "5555"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      DATABASE_SERVER_PORT: "3306"
      EUREKA_SERVER_PORT:   "8761"

  redis-server:
    image: redis:alpine
    container_name: redis-server
    ports:
      - 6379:6379

  kafka-server:
    image: spotify/kafka
    container_name: kafka-server
    mem_limit: 1073741824
    ports:
      - 2181:2181
      - 9092:9092
      
  eureka-server:
    image:   fairanb/eureka-server:dev.v2.0
    container_name: eureka-server
    ports:
      - "8761:8761"      

#TODO  
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
#    container_name: elasticsearch
#    ports:
#      - 9200:9200  