api.name: inventory
server:
  port: 8200

# Spring Cloud
spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: categoryChangeTopic
          content-type: application/json
          group: inventoryGroup