server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/longmt99/config-server
          searchPaths: customer, inventory, merchant, admin
          username: fairanb
          password: Pass!234
          default-label: dev 
#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.techwitzs: DEBUG

