api.name: inventory
server:
  port: 8801

# Spring Cloud

spring:
  cloud:
    stream:
      bindings:  
        inboundMerchantChanges:
          destination: merchantChangeTopic
          content-type: application/json
          group: inventoryGroup
          
        inboundCustomerChanges:
          destination: customerChangeTopic
          content-type: application/json
          group: inventoryGroup
        
          
                