# System Database
spring.datasource.url: jdbc:postgresql://localhost:5432/systemdb
spring.datasource.username: userdb
spring.datasource.password: Pass!234
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.class-name: org.postgresql.ds.PGSimpleDataSource
spring.jpa.show-sql: true
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.database: POSTGRESQL
spring.datasource.platform: postgres
spring.jpa.hibernate.ddl-auto: none

# Flyway 
flyway:
    enabled: false
    
# Spring Cloud
spring:
  cloud:
    stream:
      bindings:  
        inboundTenantChanges:
          destination: tenantChangeTopic
          content-type: application/json
          group: schoolGroup
        inboundUserChanges:
          destination: userChangeTopic
          content-type: application/json
          group: schoolGroup  
        output:
            destination:  schoolChangeTopic
            content-type: application/json  
        binder:
          zkNodes: localhost
          brokers: localhost
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost  

# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Zuul Proxy Server
zuul:
  server: http://localhost:5555/
  
# Security oauth2     
security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8800/users
      filter-order: 3
           
# Redis      
redis:
  server: localhost
  port: 6379
       
#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.apache: WARN
    com.multenant: DEBUG                    
                